site_name: YotsugiBot
repo_url: https://github.com/Kyousei/YotsugiBot
pages:
- Home: index.md
- About: about.md
- Guides:
    - Windows Guide: Guides/Windows Guide.md
    - Linux Guide: Guides/Linux Guide.md
- Explanation Of Features:
    - Commands List: Commands List.md
    - Music Guide: Guides/Music Guide.md
    - Contribution Guide: Guides/Contribution Guide.md
- Donate ❤❤❤: donate.md

theme: readthedocs
